# Generated by Django 4.2.9 on 2024-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalDistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('block_id', models.BigIntegerField()),
                ('transaction_hash', models.CharField(max_length=70)),
                ('log_id', models.PositiveSmallIntegerField()),
                ('input_aix_amount', models.DecimalField(decimal_places=0, max_digits=40)),
                ('distributed_aix_amount', models.DecimalField(decimal_places=0, max_digits=40)),
                ('swapped_eth_amount', models.DecimalField(decimal_places=0, max_digits=40)),
                ('distributed_eth_amount', models.DecimalField(decimal_places=0, max_digits=40)),
            ],
            options={
                'ordering': ('created_at',),
                'unique_together': {('transaction_hash', 'log_id')},
            },
        ),
    ]
