# Generated by Django 4.2.9 on 2024-03-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts_listener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totaldistributionevent',
            old_name='log_id',
            new_name='log_index',
        ),
        migrations.AlterUniqueTogether(
            name='totaldistributionevent',
            unique_together={('transaction_hash', 'log_index')},
        ),
    ]
