# Generated by Django 4.2.9 on 2024-03-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts_listener', '0002_rename_log_id_totaldistributionevent_log_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaldistributionevent',
            name='transaction_hash',
            field=models.CharField(max_length=100),
        ),
    ]
