# Generated by Django 4.2.9 on 2024-03-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts_listener', '0003_alter_totaldistributionevent_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaldistributionevent',
            name='transaction_hash',
            field=models.TextField(),
        ),
    ]
